src/Entity/Menu.php
<?php

/*
 * This file is part of Monsieur Biz' Menu plugin for Sylius.
 *
 * (c) Monsieur Biz <sylius@monsieurbiz.com>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace MonsieurBiz\SyliusMenuPlugin\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sylius\Component\Resource\Model\TimestampableTrait;

class Menu implements MenuInterface
{
    use TimestampableTrait;

    protected ?int $id = null;

    protected ?string $code = null;

    /**
     * @var Collection<int, MenuItemInterface>|null
     */
    protected ?Collection $items;

    protected ?bool $isSystem = false;

    /**
     * Menu constructor.
     */
    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    /**
     * @inheritdoc
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * @inheritdoc
     */
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    /**
     * @inheritdoc
     */
    public function getItems(): ?Collection
    {
        return $this->items;
    }

    /**
     * @inheritdoc
     */
    public function getFirstLevelItems(): array
    {
        $items = $this->getItems();
        if (null === $items) {
            return [];
        }
        $filteredItems = $items->filter(function ($item) {
            if (!$item->getParent()) {
                return $item;
            }

            return null;
        })->toArray();
        uasort($filteredItems, function ($itemA, $itemB) {
            return $itemA->getPosition() <=> $itemB->getPosition();
        });

        return array_values($filteredItems);
    }

    /**
     * @inheritdoc
     */
    public function getChilds(): array
    {
        $items = $this->getItems();
        if (null === $items) {
            return [];
        }
        $filteredItems = $items->filter(function ($item) {
            if (!$item->getParent()) {
                return $item;
            }

            return null;
        })->toArray();
        uasort($filteredItems, function ($itemA, $itemB) {
            return $itemA->getPosition() <=> $itemB->getPosition();
        });

        return array_values($filteredItems);
    }

    /**
     * @inheritdoc
     */
    public function hasItem(MenuItemInterface $item): bool
    {
        if (null === $this->items) {
            return false;
        }

        return $this->items->contains($item);
    }

    /**
     * @inheritdoc
     */
    public function addItem(MenuItemInterface $item): void
    {
        if (null !== $this->items && !$this->hasItem($item)) {
            $this->items->add($item);
        }
    }

    /**
     * @inheritdoc
     */
    public function removeItem(MenuItemInterface $item): void
    {
        if (null !== $this->items && $this->hasItem($item)) {
            $this->items->removeElement($item);
        }
    }

    /**
     * @inheritdoc
     */
    public function isSystem(): ?bool
    {
        return $this->isSystem;
    }

    /**
     * @inheritdoc
     */
    public function setIsSystem(?bool $isSystem): void
    {
        $this->isSystem = $isSystem;
    }
}

src/Entity/MenuItem.php
<?php

/*
 * This file is part of Monsieur Biz' Menu plugin for Sylius.
 *
 * (c) Monsieur Biz <sylius@monsieurbiz.com>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace MonsieurBiz\SyliusMenuPlugin\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sylius\Component\Core\Model\ImageInterface;
use Sylius\Component\Core\Model\ImagesAwareInterface;
use Sylius\Component\Resource\Model\TimestampableTrait;
use Sylius\Component\Resource\Model\TranslatableTrait;

/**
 * @method MenuItemTranslationInterface getTranslation(?string $locale = null)
 */
class MenuItem implements MenuItemInterface, ImagesAwareInterface
{
    use TimestampableTrait;

    use TranslatableTrait {
        __construct as protected initializeTranslationsCollection;
    }

    protected ?int $id = null;

    protected ?MenuInterface $menu = null;

    /**
     * @var Collection<int, MenuItemInterface>|null
     */
    protected ?Collection $items = null;

    protected ?MenuItemInterface $parent = null;

    protected ?int $position = null;
    
    protected ?string $style = null;
    
    protected ?string $imagePath = null;

    protected ?string $code = null;
    
    /**
     * @var Collection|ImageInterface
     */
    protected $images;
    
    public function getImagePath() :string
    {
        if (isset($this->images[0])){
        return $this->images[0]->getFullPath();
        }else {
            return '';
        }
    }
    
    /**
     * MenuItem constructor.
     */
    public function __construct()
    {
        $this->initializeTranslationsCollection();
        $this->items = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    /**
     * @inheritdoc
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getMenu(): ?MenuInterface
    {
        return $this->menu;
    }

    /**
     * @inheritdoc
     */
    public function setMenu(?MenuInterface $menu): void
    {
        $this->menu = $menu;
        if (null !== $menu) {
            $menu->addItem($this);
        }
    }

    /**
     * @inheritdoc
     */
    public function getParent(): ?MenuItemInterface
    {
        return $this->parent;
    }

    /**
     * @inheritdoc
     */
    public function setParent(?MenuItemInterface $parent): void
    {
        $this->parent = $parent;
    }

    /**
     * @inheritdoc
     */
    public function getPosition(): ?int
    {
        return $this->position;
    }

    /**
     * @inheritdoc
     */
    public function setPosition(?int $position): void
    {
        $this->position = $position;
    }

    /**
     * @inheritdoc
     */
    public function getItems(): ?Collection
    {
        return $this->items;
    }

    /**
     * @inheritdoc
     */
    public function setItems(?Collection $items): void
    {
        $this->items = $items;
    }

    /**
     * @inheritdoc
     */
    public function hasItem(MenuItemInterface $item): bool
    {
        if (null === $this->items) {
            return false;
        }

        return $this->items->contains($item);
    }

    /**
     * @inheritdoc
     */
    public function addItem(MenuItemInterface $item): void
    {
        if (null !== $this->items && !$this->hasItem($item)) {
            $this->items->add($item);
        }
    }

    /**
     * @inheritdoc
     */
    public function removeItem(MenuItemInterface $item): void
    {
        if (null !== $this->items && $this->hasItem($item)) {
            $this->items->removeElement($item);
        }
    }

    /**
     * @inheritdoc
     */
    public function getLabel(): ?string
    {
        return $this->getTranslation()->getLabel();
    }

    /**
     * @inheritdoc
     */
    public function getUrl(): ?string
    {
        return $this->getTranslation()->getUrl();
    }
    
     /**
     * @inheritdoc
     */
    public function getStyle(): ?string
    {
        return $this->style;
    }

    /**
     * @inheritdoc
     */
    public function setStyle($style): void
    {
        $this->style = $style;
    }
    
    /**
     * @inheritdoc
     */
    protected function createTranslation(): MenuItemTranslationInterface
    {
        return new MenuItemTranslation();
    }
    
    /**
     * {@inheritdoc}
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    /**
     * {@inheritdoc}
     */
    public function getImagesByType(string $type): Collection
    {
        return $this->images->filter(function (ImageInterface $image) use ($type) {
            return $type === $image->getType();
        });
    }

    /**
     * {@inheritdoc}
     */
    public function hasImages(): bool
    {
        return !$this->images->isEmpty();
    }

    /**
     * {@inheritdoc}
     */
    public function hasImage(ImageInterface $image): bool
    {
        return $this->images->contains($image);
    }

    /**
     * {@inheritdoc}
     */
    public function addImage(ImageInterface $image): void
    {
        $image->setOwner($this);
        $this->images->add($image);
    }

    /**
     * {@inheritdoc}
     */
    public function removeImage(ImageInterface $image): void
    {
        if ($this->hasImage($image)) {
            $image->setOwner(null);
            $this->images->removeElement($image);
        }
    }

    /**
     * @inheritdoc
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * @inheritdoc
     */
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }
}

src/Form/Type/MenuType.php
<?php

/*
 * This file is part of Monsieur Biz' Menu plugin for Sylius.
 *
 * (c) Monsieur Biz <sylius@monsieurbiz.com>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace MonsieurBiz\SyliusMenuPlugin\Form\Type;

use Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

final class MenuType extends AbstractResourceType
{
    /**
     * @inheritdoc
     *
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('code', TextType::class, [
                'label' => 'monsieurbiz_menu.ui.code',
            ])
            ->add('isSystem', CheckboxType::class, [
                'label' => 'monsieurbiz_menu.ui.is_system',
            ])
        ;
    }
}

src/Resources/views/Admin/Menu/_form.html.twig
{{ form_errors(form) }}

<div class="ui segment">
    <div class="field">
        {{ form_row(form.code) }}
    </div>
    <div class="field">
        {{ form_row(form.isSystem) }}
    </div>
</div>

src/Resources/views/Admin/Menu/_js.html.twig
<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('.js-move-link').forEach(function (link) {
            link.addEventListener('click', function (event) {
                event.stopPropagation();
                let xhr = new XMLHttpRequest();
                xhr.addEventListener( 'load', function (event) {
                    if (this.status === 200) {
                        window.location.reload();
                    }
                });
                xhr.open(event.target.dataset.method, event.target.dataset.url);
                xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                xhr.send();
                return false;
            }, false);
        });
    }, false);
</script>

src/Resources/views/Admin/Menu/_treeWithButtons.html.twig
{% import '@SyliusUi/Macro/buttons.html.twig' as buttons %}
{% import _self as tree %}

{% macro render(items) %}
    {% import '@SyliusUi/Macro/buttons.html.twig' as buttons %}
    {% import _self as tree %}

<ul>
    {% for item in items %}
    {% if item.id is not null %}
    <li data-id="{{ item.id }}" {% if item.items is not empty %}data-sylius-js-tree-parent="{{ item.id }}"{% endif %}>
        <div class="sylius-tree__item">
            <div class="sylius-tree__icon" {% if item.items is not empty %}data-sylius-js-tree-trigger="{{ item.id }}"{% endif %}>
                <i class="{{ item.items is not empty ? 'caret down' : 'angle left' }} icon"></i>
            </div>
            <div class="sylius-tree__title">
                <a href="{{ path('monsieurbiz_menu_admin_menu_item_update', {'id': item.id, 'menuId': item.menu.id}) }}"{# {% if not item.enabled %} class="text gray"{% endif %} #}>
                    {{ item.label }}
                </a>
            </div>
            <div class="sylius-tree__action">
                <div class="ui tiny basic icon top right pointing dropdown button sylius-tree__action__trigger">
                    <i class="ellipsis horizontal icon"></i>
                    <div class="menu">
                        <a class="item" href="{{ path('monsieurbiz_menu_admin_menu_item_create_for_parent', {'menuId': item.menu.id, 'parentId': item.id}) }}">
                            <i class="plus icon blue"></i>{{ 'sylius.ui.create'|trans }}
                        </a>
                        <a class="item" href="{{ path('monsieurbiz_menu_admin_menu_item_update', {'id': item.id, 'menuId': item.menu.id}) }}">
                            <i class="pencil icon grey"></i>{{ 'sylius.ui.edit'|trans }}
                        </a>

                        <div class="divider"></div>

                        {% if not loop.first %}
                            <a class="item js-move-link" data-method="PUT" data-url="{{ url('monsieurbiz_menu_admin_menu_item_move_up', {'id': item.id, 'menuId': item.menu.id}) }}">
                                <i class="arrow up icon grey"></i>{{ 'sylius.ui.move_up'|trans }}
                            </a>
                        {% endif %}
                        {% if loop.last is defined and not loop.last %}
                            <a class="item js-move-link" data-method="PUT" data-url="{{ url('monsieurbiz_menu_admin_menu_item_move_down', {'id': item.id, 'menuId': item.menu.id}) }}">
                                <i class="arrow down icon grey"></i>{{ 'sylius.ui.move_down'|trans }}
                            </a>
                        {% endif %}

                        {% if not loop.first or (loop.last is defined and not loop.last) %}
                            <div class="divider"></div>
                        {% endif %}

                        <form action="{{ path('monsieurbiz_menu_admin_menu_item_delete', {'id': item.id, 'menuId': item.menu.id}) }}" method="post" class="item">
                            <button class="ui basic negative button" type="submit" style="width: 100%;" data-requires-confirmation>
                                <i class="icon trash red"></i>{{ 'sylius.ui.delete'|trans }}
                            </button>
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_csrf_token" value="{{ csrf_token(item.id) }}" />
                        </form>

                    </div>
                </div>
            </div>
        </div>
        {% if item.items is not empty %}
            {{ tree.render(item.items) }}
        {% endif %}
    </li>
    {% endif %}
    {% endfor %}
</ul>
{% endmacro %}

<div class="ui segment sylius-tree hidden" data-sylius-js-tree>
    <a href="{{ path('monsieurbiz_menu_admin_menu_item_create_for_menu', {'menuId': menu.id}) }}" class="ui fluid labeled icon primary button">
        <i class="plus icon"></i>
        {{ 'sylius.ui.create'|trans }}
    </a>

    <div class="ui hidden divider small"></div>

    {{ tree.render(menu.firstLevelItems) }}
</div>

src/Resources/views/Admin/Menu/create.html.twig
{% extends '@SyliusAdmin/Crud/create.html.twig' %}

src/Resources/views/Admin/Menu/index.html.twig
{% extends '@SyliusAdmin/Crud/index.html.twig' %}

src/Resources/views/Admin/Menu/update.html.twig
{% extends '@SyliusAdmin/Crud/update.html.twig' %}

{% block content %}
    {{ sylius_template_event('monsieurbiz_menu.admin.menu.update.before_content', {'resource': resource}) }}

    <div class="ui grid">
        <div class="sixteen wide mobile sixteen wide tablet four wide computer column">
            {{ sylius_template_event('monsieurbiz_menu.admin.menu.update.items_tree', {'resource': resource, 'menu': resource}) }}
        </div>
        <div class="sixteen wide mobile sixteen wide tablet twelve wide computer column">
            {{ parent() }}
        </div>
    </div>

    {{ sylius_template_event('monsieurbiz_menu.admin.menu.update.after_content', {'resource': resource}) }}
{% endblock %}